import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
        rel="stylesheet"
      />

      <link rel="stylesheet" href="assets/css/fontAwesome5Pro.css" />
      <link rel="stylesheet" href="assets/css/cdheadline.css" />
      <link rel="stylesheet" href="assets/css/swiper-bundle.min.css" />
      <link rel="stylesheet" href="assets/css/style.min.css" />

      <body className={`relative custom_cursor ${inter.className}`}>
        {children}

        <Script src="assets/js/jquery-3.6.0.min.js"></Script>
        <Script src="assets/js/waypoints.min.js"></Script>
        <Script src="assets/js/tw-elements.umd.min.js"></Script>
        <Script src="assets/js/cd-headline.js"></Script>
        <Script src="assets/js/jquery.counterup.min.js"></Script>
        <Script src="assets/js/swiper-bundle.min.js"></Script>
        <Script src="assets/js/scrollIt.min.js"></Script>
        <Script src="assets/js/circle-progress.min.js"></Script>
        <Script src="assets/js/script.js"></Script>
        <Script src="assets/js/theme-mode.js"></Script>
      </body>
    </html>
  );
}
