import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Link rel="preconnect" href="https://fonts.googleapis.com" />
        <Link rel="preconnect" href="https://fonts.gstatic.com" />
        <Link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />

        <Link rel="stylesheet" href="assets/css/fontAwesome5Pro.css" />
        <Link rel="stylesheet" href="assets/css/cdheadline.css" />
        <Link rel="stylesheet" href="assets/css/swiper-bundle.min.css" />
        <Link rel="stylesheet" href="assets/css/style.min.css" />
      </head>

      <body className={inter.className}>{children}</body>

      <Script src="assets/js/jquery-3.6.0.min.js"></Script>
      <Script src="assets/js/waypoints.min.js"></Script>
      <Script src="assets/js/tw-elements.umd.min.js"></Script>
      <Script src="assets/js/cd-headline.js"></Script>
      <Script src="assets/js/jquery.counterup.min.js"></Script>
      <Script src="assets/js/swiper-bundle.min.js"></Script>
      <Script src="assets/js/scrollIt.min.js"></Script>
      <Script src="assets/js/circle-progress.min.js"></Script>
      <Script src="assets/js/script.js"></Script>
      <Script src="assets/js/theme-mode.js"></Script>
    </html>
  );
}
